//Structure: [x, y, Name, Desc, image]
const pointsOfInterest = [
  [990, 228, "Square Sea", "On the world of Auratera, SQUARE SEA is the name of an artificial body of water with an area of 250,000 km².Visually, the lake is a square-shaped body of water, measuring approximately 500 kilometers on each side. Each side corresponds to a cardinal direction on a compass, and the lake is situated 800 kilometers west of the Acablas Ruins. The origins of the lake are largely unknown, although several legends suggested that it was constructed during the early Sith Wars. However, which of the two opposing sides was responsible for its construction remained a mystery.", ""],
  [1763, 455, "Acablas Ruins", "The Acablas Ruins are a natural rock formation with an underground cave on the planet Auratera, which, as a vergence in the Force, had been the subject of a tug-of-war between the Jedi and Sith for years. Two structures belonging to both orders of the Force are situated on either side of the vergence, with a funnel-shaped entrance on a high mountain.<br />The existence of the Acablas Ruins has been recorded in ancient archives, holocrons, and diaries of Jedi and Sith curators of the site. The ruins are located exactly between the Erkeere Ridge to the east and the Square Sea of Auratera, surrounded by numerous thick-stemmed coniferous forests. The Force effect of the vergence could be felt as far as 20 kilometers away, with people drawn to the ruins. The arduous path to the ruins led directly through the forests, along 40-meter waterfalls where blue-and-white skysnares hunt some freshwater fish. A steep, rocky path behind the waterfall leads directly to the high ruins, where the raw power of the Force is felt most strongly.<br />Access to the ruins is blocked by heavy, large, and locked doors, which, once opened, lead to a large, empty chamber. Driven by the Force, winding, narrow stairs lead to an adjacent cylindrical tower. At the end of the stairs in the Cenote underground cave is a natural cavern the size of a freighter with stalactites on the ceiling. The central Cenote chamber itself is  considered the most dangerous place in the ruins, reserved only for the most powerful Force users, as it subjected the user to a test of the Force. In the numerous other chambers, which could be reached by swimming through the river, one would enter smaller caves where shining bright lights like fireflies would generate visions.", ""],
  [3408, 782, "Hriin", "During the era of the Empire, approximately 8,000 inhabitants still lived in the city. In terms of location, HRIIN was built over 3,000 kilometers from the Acablas ruins, a vergence of the Force. The city was also situated on the other side of the Erkeere Ridge, located on the high cliffs above the Hriin River, which provided the locals with a source of water, food, and transportation. HRIIN is mainly inhabited by representatives of the Twi'lek and Human species. Although HRIIN does not have any spaceports, there are smaller landing platforms for spacecraft and airspeeders. While basic maintenance and health systems exist, the energy supply proves particularly problematic due to the aging, water-powered generators, which are known to be particularly temperamental. The city itself is led by an elected chancellor.", ""],
  [3767, 674, "Hriin River", "The HRIIN RIVER is a body of water on the planet Auratera. It is located near the Erkeere Ridge and shares the same name as the settlement of Hriin. The Twi'lek and Human inhabitants of the city of Hriin primarily use the river as a source of water and food, as well as a means of transportation. The river's water also serves as a source of energy for the city, as the generators could convert the water into energy. However, the poor condition of the energy generators does not allow for a reliable power supply. The city itself is located on high cliffs above the river.", ""],
  [1002, 1217, "Senoloro", "SENOLORO is the largest city on the planet Auratera. By the time of the Empire era, the settlement is inhabited by 30,000 residents of the Duros and human species. SENOLORO is located on a large flatland island at the planet's equator, surrounded by six inland seas and their rivers. Many farms are established along the region. The city is located one-third of the way around the planet from the Acablas ruins. Senoloro has the most advanced spaceport on the planet, consisting of several hangars with old freighters that could travel to the rest of the galaxy. The city is led by a human autocrat named a Gouverneur.", ""],
  [1085, 2257, "Dewbright", "DEWBRIGHT is a city on the planet Auratera that is predominantly inhabited by Ithorians with a population of around 15,000 inhabitants. In keeping with Ithorian tradition, DEWBRIGHT is located on elevated platforms and situated in a bay on the east coast of the inland sea Crystal Sea. They could cross the water using boats and skimmers to reach the various dining establishments, which were located far from the city. The city was located in the southern hemisphere of Auratera, exactly opposite the locus of the Acablas ruins.", ""],
  [2272, 1078, "Erkeere Ridge", "The ERKEERE RIDGE is a mountain range on the Outer Rim world of Auratera. This range consists of a total of five mountains, with the largest peak, which is twice as high as the other four neighboring mountains, called Dran's Peak. The thin mountain range winds across Auratera's largest continent, forming a continuous line that extends from the North to the South Pole. The tall, jagged mountains resemble the teeth of a primitive bow saw and the mountain range can be seen from the convergence point at the Acablas Ruins. The city of Hriin was located on the other side of the mountain range. Some Skysnares have their nests there. Various Sith empires used the summit of the highest mountain in the mountain range as a ritualistic site for Sith magic.", ""],
  [1333, 2441, "Crystal Sea", "The CRYSTAL SEA is an inland sea located on the Outer Rim world of Auratera. Situated on the East coast of the sea in the Southern hemisphere of the world is a bay where the Ithorian city of Dewbright is located. Over the years, the native Ithorians used boats and skimmers to cross the sea.", ""]
];

export default pointsOfInterest;